# Generated by Django 3.1.4 on 2020-12-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=64, verbose_name='邮箱ID')),
                ('subject', models.CharField(max_length=100, verbose_name='主体')),
                ('content', models.TextField(verbose_name='内容')),
            ],
        ),
    ]
