# Generated by Django 3.1.4 on 2020-12-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='email_id',
        ),
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
